# 테마 설정
theme = "hugo-theme-codex" 
themesDir = "/themes" 

# 이 설정을 자신의 것으로
title = "offetuoso's Blog"
languageCode = "ko-KR"
baseURL = "https://offetuoso.github.io/"
copyright = "© 2021"

ignoreErrors = ["error-remote-getjson"]

# Google Analytics 식별자 추가 identifier: UA-XXXXXXXX-X
# googleAnalytics = "" 

# Optional params
[params]
  # 여기에서 Hugo 날짜 / 시간 형식 참조를 따르십시오.
  # https://gohugo.io/functions/format/#gos-layout-string
  dateFormat = "2006-01-02"

  # 소셜 계정에 대한 링크, 필요에 따라 댓글 / 댓글 제거. 지정된 항목에 대한 아이콘이 표시됩니다.
  #twitter = "https://twitter.com/<your handle>"
  github = "https://github.com/offetuoso"
  email = "mailto:offetuoso@gmail.com,offetuoso@naver.com"
  # mastodon = "https://mastodon.social/@nickname"
  # facebook = "https://facebook.com/<your handle>"
  #gitlab = "https://gitlab.com/<your handle>"
  instagram = "https://instagram.com/offetuoso"
  # linkedin = "<link to your profile>"
  # youtube = "https://www.youtube.com/channel/<your channel>"
  search = "#"
  
  # 아이콘의 제목 (툴팁으로 표시됨) 및 표시 순서.
  # 현재 다음 아이콘이 지원됩니다.
  #   "Twitter", "GitHub", "Email", "Mastodon", "Facebook", "GitLab", "Instagram", "LinkedIn", "YouTube", "search"
  iconOrder = ["GitHub", "Email", "Instagram", "search"]

  # 트위터 카드의 메타 데이터, 기본값은 params.twitter
  # twitterSite = "@<your handle>"
  # twitterAuthor = "@<your handle>"

  # 블로그 게시물의 목차에 페이지 제목을 표시하려면 true로 설정합니다.
  showPageTitleInTOC = false

# 이것은 Hugo의 기본 구문 강조 표시를 비활성화합니다. 
# 프리즘 수. Hugo의 기본 구문 강조를 사용하려는 경우
# prismjs 위에, 이것을 제거하십시오. 또한 프리즘을 제거해야합니다.
# layouts / blog / single.html의 공급 업체 스크립트.
[markup]
  [markup.highlight]
    codeFences = false
    
# 마크 다운 파일에서 원시 HTML을 허용하지 않으려면 false로 설정합니다.
  [markup.goldmark.renderer]
      unsafe = true

# 내비게이션 제어
[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog"


[outputs]
  home = ["HTML", "RSS", "JSON"]